DOMAIN = "zigbee_lock_manager"

CONF_ENABLE_NOTIFICATIONS = "enable_notifications"
CONF_ENABLE_PRESENCE_AUTOMATION = "enable_presence_automation"
CONF_ACTIVITY_EVENT_COUNT = "activity_event_count"
CONF_ENABLE_ID_LOCK_ADVANCED_CONTROLS = "enable_id_lock_advanced_controls"
CONF_BATTERY_LOW_THRESHOLD = "battery_low_threshold"

DEFAULT_ENABLE_NOTIFICATIONS = False
DEFAULT_ENABLE_PRESENCE_AUTOMATION = False
DEFAULT_ACTIVITY_EVENT_COUNT = 6
DEFAULT_ENABLE_ID_LOCK_ADVANCED_CONTROLS = False
DEFAULT_BATTERY_LOW_THRESHOLD = 30

LOCK_PROFILE_GENERIC = "generic"
LOCK_PROFILE_ID_LOCK_202_MULTI = "id_lock_202_multi"

LOCK_PROFILE_OPTIONS = {
    LOCK_PROFILE_GENERIC: "Generic ZHA Lock",
    LOCK_PROFILE_ID_LOCK_202_MULTI: "ID Lock 202 Multi",
}

ID_LOCK_202_MANUFACTURER_HINTS = ("datek", "id lock")
ID_LOCK_202_MODEL_HINTS = (
    "id lock 202",
    "id lock 202 multi",
    "idlock 202",
)
